"use client";

import { useEffect, useMemo, useState } from "react";

type Vocab={w:string;p:string;t:string;d:string;f:number;b:number;x:string};
type AudioMap=Record<string,{us?:string;uk?:string}>;
type View="learn"|"reading"|"review"|"quiz"|"grammar"|"book"|"library"|"tools";
type ReviewPlan=Record<string,{level:number;due:number;last:number}>;
type QuizMistake={id:number;answer:string;chosen:string};
const REVIEW_DAYS=[0,1,2,4,7,15,30,60];
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

const ARTICLES=[
  {tag:"成长 · B1",title:"The Courage to Begin",cn:"开始的勇气",text:"Every meaningful journey begins with a small decision. When Emma joined the school debate club, she was nervous and uncertain. She considered leaving after the first meeting, but her teacher encouraged her to stay. Through regular practice, she gradually learned to express her ideas clearly, listen to different opinions, and respond with confidence. The experience did not only improve her speaking skills. It also taught her that progress often appears when we are willing to face difficulty instead of avoiding it."},
  {tag:"自然 · B1",title:"A Forest That Remembers",cn:"会记忆的森林",text:"Scientists have discovered that a forest is more connected than it may appear. Beneath the ground, the roots of different trees exchange water and important materials through a complex network. Older trees can provide support for younger ones, especially when sunlight is limited. This hidden system helps the whole forest adapt to change. It reminds us that strength does not always come from standing alone. Sometimes, survival depends on cooperation and the quiet connections around us."},
  {tag:"科技 · B2",title:"Learning in a Digital Age",cn:"数字时代的学习",text:"Technology provides students with immediate access to a great amount of information. However, access alone does not guarantee real understanding. Learners still need to examine sources, compare different views, and consider whether an argument is reliable. A useful digital tool should encourage active thinking rather than replace it. When technology is used with a clear purpose, it can create new opportunities for education and help students become independent learners."},
];

const CLOZE={title:"The Power of Small Habits",text:["Many students hope to make great progress in a short time. However, real improvement often begins with a very small ",". A learner who reads ten minutes every day may achieve more than someone who studies for hours only before an exam. The reason is that a regular habit makes learning feel "," and reduces the pressure of starting. When difficulties appear, successful learners do not simply give ",". They examine what went wrong, adjust their plan, and continue. Over time, these repeated actions can "," confidence and turn an ordinary effort into a lasting ability."],questions:[
  {id:1,options:["decision","accident","argument","danger"],answer:"decision",analysis:"decision 表示“决定”。语境强调进步始于一个很小的决定，small decision 搭配自然。"},
  {id:2,options:["natural","impossible","silent","expensive"],answer:"natural",analysis:"每天坚持会让学习变得自然；natural 与 regular habit 构成因果关系。"},
  {id:3,options:["away","up","out","off"],answer:"up",analysis:"give up 是固定短语，表示“放弃”。"},
  {id:4,options:["build","borrow","hide","divide"],answer:"build",analysis:"build confidence 是固定搭配，表示“建立信心”。"}
]};
const GRAMMAR=[
  {title:"定语从句",rule:"关系代词 who、which、that 在从句中代替先行词，并充当主语或宾语。",example:"The student who won the prize studies English every morning.",question:"The book _____ I borrowed from the library is very useful.",options:["who","that","where","when"],answer:"that",analysis:"先行词 book 是物，关系词在从句中作 borrowed 的宾语，应使用 that 或 which。"},
  {title:"非谓语动词",rule:"动词作目的状语时常用 to do；作伴随或主动动作时常用 doing。",example:"To improve her pronunciation, Lily listens to English news every day.",question:"_____ more about the world, we should read widely.",options:["Learn","To learn","Learned","Learning by"],answer:"To learn",analysis:"句意为“为了更多地了解世界”，表示目的，使用动词不定式 To learn。"},
  {title:"虚拟语气",rule:"表示与现在事实相反的假设：If + 过去式，主句用 would/could + 动词原形。",example:"If I had more time, I would join the school English club.",question:"If I _____ you, I would accept the teacher's advice.",options:["am","was","were","will be"],answer:"were",analysis:"与现在事实相反的虚拟条件句中，be 动词通常统一使用 were。"}
];

const FUNCTION_WORDS:Record<string,{t:string;p?:string}>={a:{t:"art. 一个；一",p:"/ə/"},the:{t:"art. 这；那；这些；那些",p:"/ðə/"},to:{t:"prep. 向；到；不定式符号",p:"/tuː/"},of:{t:"prep. ……的",p:"/əv/"},and:{t:"conj. 和；并且",p:"/ænd/"},that:{t:"pron./conj. 那；那个；引导从句",p:"/ðæt/"},it:{t:"pron. 它",p:"/ɪt/"},her:{t:"pron. 她；她的",p:"/hɜːr/"},she:{t:"pron. 她",p:"/ʃiː/"},was:{t:"v. 是（be 的过去式）",p:"/wɒz/"},is:{t:"v. 是",p:"/ɪz/"},are:{t:"v. 是",p:"/ɑːr/"},with:{t:"prep. 和；具有；用",p:"/wɪð/"},when:{t:"adv./conj. 什么时候；当……时",p:"/wen/"},than:{t:"conj./prep. 比",p:"/ðæn/"},not:{t:"adv. 不；没有",p:"/nɒt/"},but:{t:"conj. 但是",p:"/bʌt/"},can:{t:"modal v. 能；可以",p:"/kæn/"},from:{t:"prep. 从；来自",p:"/frɒm/"},as:{t:"adv./conj./prep. 像；作为；当……时",p:"/æz/"}};

function normalize(raw:string,map:Map<string,Vocab>){
  const w=raw.toLowerCase().replace(/[^a-z'-]/g,"");
  if(map.has(w))return w;
  const irregular:Record<string,string>={begins:"begin",joined:"join",was:"be",leaving:"leave",encouraged:"encourage",learned:"learn",taught:"teach",appears:"appear",avoiding:"avoid",scientists:"scientist",discovered:"discover",trees:"tree",older:"old",younger:"young",ones:"one",helps:"help",reminds:"remind",connections:"connection",provides:"provide",students:"student",learners:"learner",sources:"source",views:"view",depends:"depend",used:"use"};
  if(irregular[w]&&map.has(irregular[w]))return irregular[w];
  for(const s of ["ing","ied","ed","es","s"]){if(w.endsWith(s)){let root=w.slice(0,-s.length)+(s==="ied"?"y":"");if(map.has(root))return root;if(map.has(root+"e"))return root+"e";}}
  return w;
}

function ClickableText({text,map,onWord}:{text:string;map:Map<string,Vocab>;onWord:(w:string)=>void}){
  return <>{text.split(/([A-Za-z][A-Za-z'-]*)/g).map((part,i)=>/^[A-Za-z]/.test(part)?<button key={i} className="article-word" onClick={()=>onWord(normalize(part,map))}>{part}</button>:<span key={i}>{part}</span>)}</>;
}

async function playWord(word:string,audioMap:AudioMap,setToast:(s:string)=>void){
  try{const recording=audioMap[word];const url=recording?.us||recording?.uk;if(!url)throw new Error();await new Audio(url).play()}catch{setToast("录音加载失败，请检查网络后重试");setTimeout(()=>setToast(""),1800)}
}

export default function Home(){
  const [words,setWords]=useState<Vocab[]>([]); const [audioMap,setAudioMap]=useState<AudioMap>({}); const [view,setView]=useState<View>("learn");
  const [active,setActive]=useState("achieve"); const [known,setKnown]=useState<string[]>([]); const [saved,setSaved]=useState<string[]>([]);
  const [article,setArticle]=useState(0); const [query,setQuery]=useState(""); const [limit,setLimit]=useState(60); const [toast,setToast]=useState(""); const [loadingAudio,setLoadingAudio]=useState(false); const [reviewPlan,setReviewPlan]=useState<ReviewPlan>({}); const [checkins,setCheckins]=useState<string[]>([]); const [articleAudio,setArticleAudio]=useState<"idle"|"playing"|"paused">("idle"); const [mistakes,setMistakes]=useState<QuizMistake[]>([]);
  useEffect(()=>{fetch("/gaokao-vocab.json").then(r=>r.json()).then((d:Vocab[])=>{setWords(d);setActive(d[0]?.w||"achieve")});fetch("/audio-map.json").then(r=>r.json()).then(setAudioMap);try{setKnown(JSON.parse(localStorage.getItem("yujing-known")||"[]"));setSaved(JSON.parse(localStorage.getItem("yujing-saved")||"[]"));setReviewPlan(JSON.parse(localStorage.getItem("yujing-review")||"{}"));setCheckins(JSON.parse(localStorage.getItem("yujing-checkins")||"[]"));setMistakes(JSON.parse(localStorage.getItem("yujing-mistakes")||"[]"))}catch{}},[]);
  useEffect(()=>{if(words.length){localStorage.setItem("yujing-known",JSON.stringify(known));localStorage.setItem("yujing-saved",JSON.stringify(saved));localStorage.setItem("yujing-review",JSON.stringify(reviewPlan));localStorage.setItem("yujing-checkins",JSON.stringify(checkins));localStorage.setItem("yujing-mistakes",JSON.stringify(mistakes))}},[known,saved,reviewPlan,checkins,mistakes,words.length]);
  const map=useMemo(()=>new Map(words.map(w=>[w.w,w])),[words]); const item=map.get(active); const index=item?words.indexOf(item):0;
  const stage=index<1200?"高频":index<2400?"中频":"低频"; const daily=words.slice(Math.floor(index/20)*20,Math.floor(index/20)*20+20);
  const dueWords=useMemo(()=>known.filter(w=>!reviewPlan[w]||reviewPlan[w].due<=Date.now()).map(w=>map.get(w)).filter(Boolean) as Vocab[],[known,reviewPlan,map]);
  const search=useMemo(()=>{const q=query.trim().toLowerCase();return (q?words.filter(w=>w.w.includes(q)||w.t.includes(query.trim())):words).slice(0,limit)},[words,query,limit]);
  function selectWord(w:string){setActive(w);if(view!=="learn")setView("reading");}
  function checkIn(){const day=dateKey();setCheckins(c=>c.includes(day)?c:[...c,day])}
  function markKnown(){checkIn();if(!known.includes(active)){setKnown(k=>[...k,active]);setReviewPlan(p=>({...p,[active]:{level:0,due:Date.now(),last:Date.now()}}))}const next=words[Math.min(index+1,words.length-1)];if(next)setActive(next.w);}
  function toggleSaved(){setSaved(s=>s.includes(active)?s.filter(x=>x!==active):[...s,active]);setToast(saved.includes(active)?"已移出生词本":"已加入生词本");setTimeout(()=>setToast(""),1400)}
  async function playAudio(){setLoadingAudio(true);await playWord(active,audioMap,setToast);setLoadingAudio(false)}
  function readArticle(){if(articleAudio==="playing"){speechSynthesis.pause();setArticleAudio("paused");return}if(articleAudio==="paused"){speechSynthesis.resume();setArticleAudio("playing");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(ARTICLES[article].text);u.lang="en-US";u.rate=.88;u.onend=()=>setArticleAudio("idle");u.onerror=()=>setArticleAudio("idle");speechSynthesis.speak(u);setArticleAudio("playing")}
  function finishReview(word:string,correct:boolean){checkIn();const old=reviewPlan[word]?.level||0;const level=correct?Math.min(old+1,REVIEW_DAYS.length-1):0;const days=correct?REVIEW_DAYS[level]:1;setReviewPlan(p=>({...p,[word]:{level,due:Date.now()+days*86400000,last:Date.now()}}))}
  const display=item|| (FUNCTION_WORDS[active]?{w:active,p:FUNCTION_WORDS[active].p||"",t:FUNCTION_WORDS[active].t,d:"文章中的常用功能词",f:0,b:0,x:""}:null);

  return <main className="app-shell">
    <header className="app-header"><a className="brand" href="#" onClick={()=>setView("learn")}><span>境</span><div>语境<small>高中 3500 词</small></div></a><nav>{([['learn','学习'],['reading','文章'],['review','默写'],['quiz','完形'],['grammar','语法'],['book','生词本'],['library','词库'],['tools','工具']] as [View,string][]).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>{speechSynthesis.cancel();setArticleAudio("idle");setView(id)}}>{label}{id==="book"&&saved.length>0?<b>{saved.length}</b>:id==="review"&&dueWords.length>0?<b>{dueWords.length}</b>:id==="quiz"&&mistakes.length>0?<b>{mistakes.length}</b>:null}</button>)}</nav><div className="streak">✦ 已打卡 {checkins.length} 天</div></header>
    {view==="learn"&&<><section className="dashboard"><div><p className="eyebrow">今日学习 · {stage}阶段</p><h1>在语境里，<em>真正记住</em>每一个词。</h1><p>严格收录 {words.length||"3,500"} 个高中核心词，每个词均配有真人录音。</p></div><div className="overall"><strong>{known.length}</strong><span>/ {words.length||3500} 已掌握</span><div><i style={{width:`${words.length?known.length/words.length*100:0}%`}}/></div><button className="review-now" onClick={()=>setView("review")}>今日待复习 {dueWords.length} 词 →</button></div></section><section className="daily-strip"><div><span>今日 20 词</span><strong>{Math.min(known.filter(w=>daily.some(d=>d.w===w)).length,20)} / 20</strong></div>{daily.map((w,i)=><button key={w.w} className={`${active===w.w?"active":""} ${known.includes(w.w)?"known":""}`} onClick={()=>setActive(w.w)}><small>{i+1}</small>{w.w}</button>)}</section><StudyCard display={display} index={index} total={words.length} stage={stage} saved={saved.includes(active)} loading={loadingAudio} onAudio={playAudio} onSave={toggleSaved} onKnow={markKnown}/><section className="reading-teaser"><div><p className="eyebrow">语境阅读</p><h2>把今天的词放回一篇文章里</h2><p>文章中的每个英文单词都能点击查询和收藏。</p></div><button onClick={()=>setView("reading")}>开始阅读 →</button></section></>}
    {view==="reading"&&<section className="reader-layout"><div className="article-list">{ARTICLES.map((a,i)=><button key={a.title} className={article===i?"active":""} onClick={()=>{speechSynthesis.cancel();setArticleAudio("idle");setArticle(i)}}><small>{a.tag}</small><strong>{a.title}</strong><span>{a.cn}</span></button>)}</div><article className="reader"><p className="eyebrow">{ARTICLES[article].tag} · 全文可点词</p><h1>{ARTICLES[article].title}</h1><h2>{ARTICLES[article].cn}</h2><button className="article-audio" onClick={readArticle}>{articleAudio==="playing"?"⏸ 暂停发音":articleAudio==="paused"?"▶ 继续发音":"▶ 收听全文"}</button><div className="article-copy"><ClickableText text={ARTICLES[article].text} map={map} onWord={selectWord}/></div><p className="reader-hint">轻触任何英文单词，即可在右侧查看并学习</p></article><StudyCard compact display={display} index={index} total={words.length} stage={stage} saved={saved.includes(active)} loading={loadingAudio} onAudio={playAudio} onSave={toggleSaved} onKnow={markKnown}/></section>}
    {view==="review"&&<Dictation words={dueWords} plan={reviewPlan} onResult={finishReview} onAudio={async w=>{setActive(w);await playWord(w,audioMap,setToast)}}/>}
    {view==="quiz"&&<ClozeQuiz map={map} mistakes={mistakes} onMistakes={setMistakes} onSaveWord={w=>{if(!map.has(w)){setToast("这个词暂未收录到高中词库");setTimeout(()=>setToast(""),1400);return}setSaved(s=>s.includes(w)?s:[...s,w]);setToast("已加入生词本："+w);setTimeout(()=>setToast(""),1400)}}/>} 
    {view==="grammar"&&<GrammarPractice map={map} onSaveWord={w=>{if(map.has(w)){setSaved(s=>s.includes(w)?s:[...s,w]);setToast("已加入生词本："+w)}else setToast("这个词暂未收录到高中词库");setTimeout(()=>setToast(""),1400)}}/>}
    {view==="book"&&<WordGrid title="我的生词本" subtitle={`已收藏 ${saved.length} 个词，点击继续学习`} words={saved.map(w=>map.get(w)).filter(Boolean) as Vocab[]} known={known} onWord={w=>{setActive(w);setView("learn")}} empty="还没有生词。阅读文章时，点击单词并加入生词本。"/>}
    {view==="library"&&<section className="library"><div className="library-head"><div><p className="eyebrow">完整高考词库</p><h1>{words.length.toLocaleString()} 个词条</h1><p>按现代语料词频排列：高频 → 中频 → 低频</p></div><label>⌕<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(60)}} placeholder="搜索英文或中文释义"/></label></div><WordGrid words={search} known={known} onWord={w=>{setActive(w);setView("learn")}} empty="没有找到这个词。"/>{search.length<(query?words.filter(w=>w.w.includes(query.toLowerCase())||w.t.includes(query)).length:words.length)&&<button className="load-more" onClick={()=>setLimit(x=>x+60)}>加载更多</button>}</section>}
    {view==="tools"&&<Tools words={words} map={map} checkins={checkins} onWord={w=>setActive(w)} onCheckIn={checkIn}/>} 
    <footer><span>语境 · 高中英语 3500 词</span><span>词典：ECDICT · 真人录音：endict（MIT）</span></footer>{toast&&<div className="toast">✓ {toast}</div>}
  </main>;
}

function StudyCard({display,index,total,stage,saved,loading,onAudio,onSave,onKnow,compact=false}:{display:Vocab|null;index:number;total:number;stage:string;saved:boolean;loading:boolean;onAudio:()=>void;onSave:()=>void;onKnow:()=>void;compact?:boolean}){
  if(!display)return <aside className={`study-card ${compact?"compact":""}`}><p>词库加载中…</p></aside>;
  return <aside className={`study-card ${compact?"compact":""}`}><div className="card-top"><span>{stage}词 · {Math.max(index+1,1)}/{total||3500}</span><button onClick={onSave} aria-label="收藏">{saved?"★":"☆"}</button></div><h2>{display.w}</h2><div className="pronounce"><span>{display.p||"音标整理中"}</span><button onClick={onAudio} disabled={loading}>{loading?"加载中…":"▶ 真人发音"}</button></div><div className="definition"><strong>{display.t||"暂无中文释义"}</strong>{display.d&&<p>{display.d}</p>}</div><div className="card-actions"><button onClick={onSave}>{saved?"已加入生词本":"我不认识"}</button><button className="know" onClick={onKnow}>我认识 →</button></div></aside>;
}

function WordGrid({title,subtitle,words,known,onWord,empty}:{title?:string;subtitle?:string;words:Vocab[];known:string[];onWord:(w:string)=>void;empty:string}){return <section className="word-section">{title&&<div className="section-title"><p className="eyebrow">复习</p><h1>{title}</h1><p>{subtitle}</p></div>}{!words.length?<div className="empty">{empty}</div>:<div className="word-grid">{words.map((w,i)=><button key={w.w} onClick={()=>onWord(w.w)}><small>{i+1}</small><div><strong>{w.w}</strong><span>{w.p}</span><p>{w.t.split(/[；\n]/)[0]}</p></div><i>{known.includes(w.w)?"✓":"→"}</i></button>)}</div>}</section>}

function Dictation({words,plan,onResult,onAudio}:{words:Vocab[];plan:ReviewPlan;onResult:(word:string,correct:boolean)=>void;onAudio:(word:string)=>void}){
  const [input,setInput]=useState("");const [feedback,setFeedback]=useState<""|"right"|"wrong">("");const current=words[0];
  useEffect(()=>{setInput("");setFeedback("");if(current)onAudio(current.w)},[current?.w]);
  if(!current)return <section className="review-page"><div className="review-done"><span>✓</span><p className="eyebrow">今日复习完成</p><h1>记忆需要恰到好处的重逢。</h1><p>系统会在第 1、2、4、7、15、30、60 天安排下一次默写。</p></div><div className="memory-line">{REVIEW_DAYS.slice(1).map((d,i)=><div key={d}><i>{i+1}</i><strong>第 {d} 天</strong><span>{i<REVIEW_DAYS.length-2?"→":""}</span></div>)}</div></section>;
  function submit(e:React.FormEvent){e.preventDefault();if(!input.trim())return;const ok=input.trim().toLowerCase()===current.w.toLowerCase();setFeedback(ok?"right":"wrong");setTimeout(()=>{onResult(current.w,ok);setFeedback("");setInput("")},1200)}
  return <section className="review-page"><div className="review-head"><div><p className="eyebrow">艾宾浩斯复习 · 听音默写</p><h1>今日待复习 {words.length} 词</h1><p>听发音，写出完整单词。答对后进入下一记忆间隔，答错则明天再次出现。</p></div><div className="review-level">第 {(plan[current.w]?.level||0)+1} 次复习</div></div><div className={`dictation-card ${feedback}`}><button className="big-audio" onClick={()=>onAudio(current.w)}>▶</button><span>点击再次播放真人发音</span><p>{current.t.split(/[；\n]/)[0]}</p><form onSubmit={submit}><input autoFocus autoComplete="off" value={input} onChange={e=>setInput(e.target.value)} placeholder="输入你听到的单词"/><button>检查答案</button></form>{feedback==="right"&&<div className="answer right">✓ 正确！{current.w}</div>}{feedback==="wrong"&&<div className="answer wrong">正确拼写：<strong>{current.w}</strong></div>}<small>进度 {Math.max(1,Object.keys(plan).length-words.length+1)} / {Object.keys(plan).length}</small></div><div className="memory-line compact-line">{REVIEW_DAYS.slice(1).map((d,i)=><div key={d} className={(plan[current.w]?.level||0)>=i+1?"done":""}><i>{i+1}</i><strong>{d}天</strong><span>{i<REVIEW_DAYS.length-2?"→":""}</span></div>)}</div></section>
}

function GrammarPractice({map,onSaveWord}:{map:Map<string,Vocab>;onSaveWord:(w:string)=>void}){
  const [lesson,setLesson]=useState(0);const [choice,setChoice]=useState("");const [checked,setChecked]=useState(false);const item=GRAMMAR[lesson];
  function change(i:number){setLesson(i);setChoice("");setChecked(false)}
  return <section className="grammar-page"><div className="grammar-head"><p className="eyebrow">高中英语语法</p><h1>从例句理解规则，再用练习真正掌握。</h1><p>例句中的英文单词可以点击加入生词本。</p></div><div className="grammar-layout"><aside>{GRAMMAR.map((g,i)=><button key={g.title} className={lesson===i?"active":""} onClick={()=>change(i)}><small>专题 {i+1}</small><strong>{g.title}</strong></button>)}</aside><article className="grammar-card"><p className="eyebrow">规则讲解</p><h2>{item.title}</h2><p className="grammar-rule">{item.rule}</p><div className="grammar-example"><small>例句 · 点击单词可收藏</small><p><ClickableText text={item.example} map={map} onWord={onSaveWord}/></p></div><section className="grammar-question"><h3>对应练习</h3><p>{item.question}</p><div>{item.options.map(o=><button key={o} className={choice===o?"selected":""} disabled={checked} onClick={()=>setChoice(o)}>{o}</button>)}</div><button className="grammar-check" disabled={!choice} onClick={()=>setChecked(true)}>检查并查看解析</button>{checked&&<div className={choice===item.answer?"grammar-result right":"grammar-result wrong"}><strong>{choice===item.answer?"✓ 回答正确":"✕ 正确答案："+item.answer}</strong><p>{item.analysis}</p></div>}</section></article></div></section>
}

function ClozeQuiz({map,mistakes,onMistakes,onSaveWord}:{map:Map<string,Vocab>;mistakes:QuizMistake[];onMistakes:(m:QuizMistake[])=>void;onSaveWord:(w:string)=>void}){
  const [answers,setAnswers]=useState<Record<number,string>>({});
  const [submitted,setSubmitted]=useState(false);
  const score=CLOZE.questions.filter(q=>answers[q.id]===q.answer).length;
  function submit(){if(Object.keys(answers).length<CLOZE.questions.length)return;const wrong=CLOZE.questions.filter(q=>answers[q.id]!==q.answer).map(q=>({id:q.id,answer:q.answer,chosen:answers[q.id]}));onMistakes(wrong);setSubmitted(true)}
  return <section className="quiz-page"><div className="quiz-head"><div><p className="eyebrow">高中英语 · 完形填空</p><h1>{CLOZE.title}</h1><p>选择最符合上下文的词。文章中不认识的英文单词可直接点击加入生词本。</p></div>{submitted&&<strong>{score} / {CLOZE.questions.length}</strong>}</div><article className="cloze-card"><p className="cloze-hint">轻触文章中的英文单词即可加入生词本</p><div className="cloze-copy">{CLOZE.text.map((part,i)=><span key={i}><ClickableText text={part} map={map} onWord={onSaveWord}/>{i<CLOZE.questions.length&&<b className={submitted?(answers[i+1]===CLOZE.questions[i].answer?"right":"wrong"):""}>{i+1}. {answers[i+1]||"______"}</b>}</span>)}</div><div className="cloze-questions">{CLOZE.questions.map(q=><section key={q.id} className={submitted&&answers[q.id]!==q.answer?"mistake":""}><h3>{q.id}. 选择答案</h3><div>{q.options.map(o=><button key={o} className={answers[q.id]===o?"selected":""} disabled={submitted} onClick={()=>setAnswers(a=>({...a,[q.id]:o}))}>{o}</button>)}</div>{submitted&&<p><strong>{answers[q.id]===q.answer?"✓ 正确":"✕ 正确答案："+q.answer}</strong><span>{q.analysis}</span></p>}</section>)}</div>{!submitted?<button className="quiz-submit" disabled={Object.keys(answers).length<CLOZE.questions.length} onClick={submit}>提交并自动解析</button>:<button className="quiz-submit" onClick={()=>{setAnswers({});setSubmitted(false)}}>再做一次</button>}</article>{mistakes.length>0&&<section className="mistake-book"><div><p className="eyebrow">错题本</p><h2>需要重新掌握的题目</h2></div>{mistakes.map(m=>{const q=CLOZE.questions.find(x=>x.id===m.id)!;return <article key={m.id}><strong>第 {m.id} 题：{m.chosen} → {m.answer}</strong><p>{q.analysis}</p></article>})}<button onClick={()=>onMistakes([])}>清空错题本</button></section>}</section>
}

function Tools({words,map,checkins,onWord,onCheckIn}:{words:Vocab[];map:Map<string,Vocab>;checkins:string[];onWord:(w:string)=>void;onCheckIn:()=>void}){
  const [pasted,setPasted]=useState("");const [generated,setGenerated]=useState("");const [used,setUsed]=useState<string[]>([]);const now=new Date();
  const year=now.getFullYear(),month=now.getMonth(),days=new Date(year,month+1,0).getDate(),offset=(new Date(year,month,1).getDay()+6)%7;
  const calendar=[...Array(offset).fill(null),...Array.from({length:days},(_,i)=>i+1)];
  function generate(){const list=[...new Set(pasted.toLowerCase().match(/[a-z][a-z'-]*/g)||[])].filter(w=>map.has(w)).slice(0,30);setUsed(list);if(!list.length){setGenerated("");return}const open="On a quiet afternoon, our class began a special language project. Instead of memorizing isolated terms, we tried to discover how words could connect with real ideas. ";const sentences=[];for(let i=0;i<list.length;i+=3){const group=list.slice(i,i+3).map(w=>`“${w}”`);sentences.push(`In the next discussion, we explored ${group.length===1?group[0]:group.slice(0,-1).join(", ")+" and "+group.at(-1)} through examples, questions and a short story.`)}setGenerated(open+sentences.join(" ")+" By the end, every word had become part of a meaningful learning experience.")}
  function readGenerated(){if(!generated)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(generated.replace(/[“”]/g,""));u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}
  return <section className="tools-page"><div className="tools-title"><p className="eyebrow">学习工具</p><h1>把坚持看得见，把单词放进故事里。</h1></div><div className="tools-grid"><section className="calendar-card"><div className="tool-head"><div><p className="eyebrow">学习打卡</p><h2>{year} 年 {month+1} 月</h2></div><strong>{checkins.length}<small>累计天数</small></strong></div><div className="weekdays">{["一","二","三","四","五","六","日"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{calendar.map((day,i)=>day?<div key={i} className={`${checkins.includes(dateKey(new Date(year,month,day)))?"checked":""} ${day===now.getDate()?"today":""}`}><span>{day}</span>{checkins.includes(dateKey(new Date(year,month,day)))&&<i>✓</i>}</div>:<div key={i}/>)}</div><button className="checkin-button" disabled={checkins.includes(dateKey())} onClick={onCheckIn}>{checkins.includes(dateKey())?"✓ 今天已打卡":"完成今天的学习打卡"}</button></section><section className="generator-card"><div className="tool-head"><div><p className="eyebrow">语境文章生成器</p><h2>粘贴你想学习的单词</h2></div><span>最多 30 词</span></div><textarea value={pasted} onChange={e=>setPasted(e.target.value)} placeholder="例如：achieve, benefit, consider, provide&#10;支持空格、逗号或换行分隔"/><button className="generate-button" onClick={generate}>生成语境文章 →</button>{pasted&&used.length===0&&<p className="generator-error">没有找到词库中的有效单词，请检查拼写。</p>}</section></div>{generated&&<section className="generated-article"><div className="generated-head"><div><p className="eyebrow">为你生成 · {used.length} 个目标词</p><h2>A Vocabulary Project</h2></div><button onClick={readGenerated}>▶ 收听全文</button></div><div className="article-copy"><ClickableText text={generated} map={map} onWord={onWord}/></div><div className="target-chips">{used.map(w=><button key={w} onClick={()=>onWord(w)}><strong>{w}</strong><span>{map.get(w)?.t.split(/[；\n]/)[0]}</span></button>)}</div></section>}</section>
}
